#!/bin/bash

echo -e "Testing branch $1\n"

git checkout $1

rm -rf bin/*
javac -d bin/ src/net/rlenar/ahocorasick/*
javac -cp "bin/net/rlenar/ahocorasick/:$JUNIT" -d bin/ test/net/rlenar/ahocorasick/*

java -cp "bin/:$JUNIT" net.rlenar.ahocorasick.BasicTest

echo -e "\nTesing branch $2\n"

git checkout $2

rm -rf bin/*
javac -d bin/ src/net/rlenar/ahocorasick/*
javac -cp "bin/net/rlenar/ahocorasick/:$JUNIT" -d bin/ test/net/rlenar/ahocorasick/*

java -cp "bin/:$JUNIT" net.rlenar.ahocorasick.BasicTest


