#!/bin/bash

git checkout $0

javac -d bin/net/rlenar/ahocorasick/ src/net/rlenar/ahocorasick/*
javac -cp bin/net/rlenar/ahocorasick/;$JUNIT -d bin/net/rlenar/ahocorasick/ test/net/rlenar/ahocorasick/*

java -cp bin/ net.rlenar.ahocorasick.BasicTest

git checkout $1

javac -d bin/net/rlenar/ahocorasick/ src/net/rlenar/ahocorasick/*
javac -cp bin/net/rlenar/ahocorasick/;$JUNIT -d bin/net/rlenar/ahocorasick/ test/net/rlenar/ahocorasick/*

java -cp bin/ net.rlenar.ahocorasick.BasicTest


